name: Deploy Laravel App to EC2

on:
  push:
    branches:
      - dev
jobs:
  build-deploy:
    environment: deploy
    runs-on: ubuntu-latest
    container:
      image: php:7.4-cli
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y zip unzip git libzip-dev libpng-dev pkg-config libsodium-dev libsodium23
          docker-php-ext-install zip pdo pdo_mysql gd sodium 
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          composer install --no-dev --optimize-autoloader
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          aws --version
      - name: Package
        run: zip -r deploy.zip . -x "*.git*" ".github/*" "tests/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp deploy.zip s3://awefilmstagebuild/deploy-${{ github.sha }}.zip
